### ISSUE TITLE
Linking error when cross-compile for arm-unknown-linux-gnueabihf target

### ISSUE THREAD

**Issue by ngoquang2708** [Alexhuszagh/cross_dbus_pkgconfig#1]
Use ```ghcr.io/cross-rs/arm-unknown-linux-gnueabihf:main``` in ```armhf.Dockerfile``` and change ```target.armv7-unknown-linux-gnueabihf``` to ```target.arm-unknown-linux-gnueabihf``` in ```Cross.toml```. Then compile with ```cross build --target arm-unknown-linux-gnueabihf``` cause linking error with ```libsystemd```.

```
 /x-tools/arm-unknown-linux-gnueabihf/lib/gcc/arm-unknown-linux-gnueabihf/8.3.0/../../../../arm-unknown-linux-gnueabihf/bin/ld: warning: libsystemd.so.0, needed by /usr/lib/arm-linux-gnueabihf/libdbus-1.so, not found (try using -rpath or -rpath-link)
          /x-tools/arm-unknown-linux-gnueabihf/lib/gcc/arm-unknown-linux-gnueabihf/8.3.0/../../../../arm-unknown-linux-gnueabihf/bin/ld: /usr/lib/arm-linux-gnueabihf/libdbus-1.so: undefined reference to `sd_listen_fds@LIBSYSTEMD_209'
          /x-tools/arm-unknown-linux-gnueabihf/lib/gcc/arm-unknown-linux-gnueabihf/8.3.0/../../../../arm-unknown-linux-gnueabihf/bin/ld: /usr/lib/arm-linux-gnueabihf/libdbus-1.so: undefined reference to `sd_is_socket@LIBSYSTEMD_209'
```

**Comment by Alexhuszagh** [comment]
This is because `arm-unknown-linux-gnueabihf` does not use system packages and does not have `PKG_CONFIG_PATH` to the system packages installed by default. This is since the Debian repositories only have packages for ARMv7, not ARMv6, and so we must use a crosstool-based image.

There's no good way to get around this except to build from source, or provide pre-built binaries. [vcpkg](https://vcpkg.io/en/getting-started.html) may be useful here.

**Comment by ngoquang2708** [comment]
```
Debian repositories only have packages for ARMv7, not ARMv6
```
Thanks for pointing that out. and for mentioning vcpkg.
